#Anemones with same anem_obs and multiple sites
#Portion of code in AmenVisitationTable

rm(list=ls())

#################### Set-up: ####################
#library(RCurl) #allows running R scripts from GitHub
library(RMySQL) #might need to load this to connect to the database?
library(dplyr)

#load data.frame generated by code in AnemVisitationTable (loading it rather than recreating it here b/c takes ~10 min to get the lat/lon info)
load(file="AnemAllInfowLatLon_15Nov2017.RData") #loads data frame called "anem.AllInfo" with dive_table_id, anem_table_id, anem_id, anem_obs, old_anem_id, date, dive_type, site, year, anem_id_unq (either anem_obs if has one, or anem_id w/"id" appended at the front), lat, lon for that observation (if any duplicate gps points during visit, take those, otherwise average)

#################### Running things: ####################

#grouping by anem_id_unq (so anem_obs if has one, otherwise anem_id w/"id" in front), finding mean and sd of lat and lon measurements and nvisits
#not all visits have a GPS measurement so find the number of visits that do...
anem.LatLon <- anem.AllInfo %>% filter(!is.na(lat)) %>% group_by(anem_id_unq) %>% summarize(meanlat = mean(lat), sdlat = sd(lat), meanlon = mean(lon, na.rm = TRUE), sdlon = sd(lon, na.rm = TRUE), ngps = n())
anem.IDUnqSites <- distinct(anem.AllInfo[c("anem_id_unq", "site")]) #pull out list of anem_id_unqs and their sites with only one row per each
anem.LatLon <- left_join(anem.LatLon, anem.IDUnqSites, by = 'anem_id_unq') #add in site

#some anem_id_unqs show up at multiple sites - see which ones:
n_occur <- data.frame(table(anem.LatLon$anem_id_unq)) #make a table of the anem_ids and the frequency with which they occur (to see why anem.Sites has more than anem.IDs)
n_occurMultiple <- n_occur[n_occur$Freq > 1,] #find the ones that occur more than once

#pull out the info on the ones that appear in multiple sites
multiSiteAnemObs <- anem.AllInfo %>% filter(anem_id_unq %in% n_occurMultiple$Var1) %>% arrange(anem_obs)

#pull out the records for just one of the anem_obs2/
anem.AllInfo %>% filter(anem_id_unq == 96)

#Summary (anem_obs and the sites):
# 51: Palanas + Poroc Rose
# 100, 101: Cabatoan + Magbangon
# 108: Cabatoan + Palanas
# 145, 57: Palanas + Sitio Baybayon
# 159: Hicgop South + Palanas
# 162, 203: Sitio Baybayon + Wangag
# 163: Caridad Proper + Wangag
# 166, 197, 198: Palanas + Wangag
# 170: San Agustin + Sitio Baybayon
# 184, 193: Sitio Baybayon + Tamakin Dacot
# 204: Haina + Sitio Baybayon
# 81: Hicgop South + Magbangon
# 96: Magbangon + Palanas







