# Fitting a growth curve 

#################### Set-up: ####################

# Pull data, functions, constants 
source(here::here("Code", "Constants_database_common_functions.R"))

# Load additional packages
library(ggplot2)
library(cowplot)

# Set parameters
# Pull out a set where fish were captured about a year apart
year_lower_limit = 345
year_upper_limit = 385

month_days = 30 

#################### Functions: ####################

# Function to find the first size, second size, and time elapsed for a pair of encounters 
findRecapPair <- function(recaps_df, marked_fish_df, encounter1, encounter2) {
  out <- marked_fish_df %>%
    filter(fish_id %in% recaps_df$fish_id) %>% 
    group_by(fish_id) %>%
    arrange(date) %>%
    summarize(L1 = size[encounter1],
              L2 = size[encounter2],
              tal = as.Date(date[encounter2]) - as.Date(date[encounter1]))
  return(out)
}

# Choose one recap pair per fish, run lm, save coefficients, pairs already selected for particular time limit
chooseRecapFitModel_TimeLimitPreFiltered <- function(n_runs, pairs_df, multiple_year_pairs) {  # pairs df is something like recap_pairs_year with all pairs caught within the time frame, multiple_year_pairs is like multiple_year_recap_fish filtered for n_caps > 1
  
  # Set up an output data frame
  out = data.frame(run = seq(from=1, to=n_runs, by=1),
                   intercept_est = NA,
                   slope_est = NA,
                   intercept_se = NA,
                   slope_se = NA)
  
  # Pull out the pairs that were only caught once
  pairs_1_set <- pairs_df %>% 
    filter(fish_id %in% ((multiple_year_pairs %>% filter(n_year_caps == 1))$fish_id))
  
  # In for each run, choose pairs, run model, save output
  for(i in 1:n_runs) {
    
    # Choose a pair for the fish caught multiple times
    set_selected <- multiple_year_pairs %>%
      filter(n_year_caps > 1) %>%
      mutate(pair_chosen = NA)
    
    # Create a data frame to collect the chosen pairs from the fish with 2 or more (this is a little weird, should figure out a better way...)
    pairs_2plus_set <- data.frame(fish_id = NA, L1 = NA, L2 = NA,
                                  tal_days = NA, tal = NA, growth = NA,
                                  growth_per_year = NA, L2_one_year_later = NA)
    
    for(j in 1:length(set_selected$fish_id)) {
      
      # select a pair
      set_selected$pair_chosen[j] = base::sample(1:set_selected$n_year_caps[j], 1)
      
      # pull out the info for the pairs for that fish
      pair_group <- pairs_df %>%
        filter(fish_id == set_selected$fish_id[j])
      
      # add the selected to the data frame
      pairs_2plus_set <- rbind(pairs_2plus_set, pair_group[set_selected$pair_chosen[j],])
      
    }
    
    # Remove that extra NA line at the top, join pair sets together
    all_pairs <- rbind(pairs_1_set, pairs_2plus_set[-1,])
    
    # Fit model, save output
    model_out <- lm(L2 ~ L1, data = all_pairs)
    
    out$intercept_est[i] = coef(summary(model_out))["(Intercept)", "Estimate"]
    out$slope_est[i] = coef(summary(model_out))["L1", "Estimate"]
    out$intercept_se[i] = coef(summary(model_out))["(Intercept)", "Std. Error"]
    out$slope_se[i] = coef(summary(model_out))["L1", "Std. Error"]
  }
  return(out)
}

#################### Running things: ####################

# Filter out just marked fish, using fish_indiv
marked_fish <- allfish_caught %>%  
  filter(!is.na(fish_indiv))  # only use fish that have been "marked" in some way and assigned a fish_indiv id in fish_obs table generated by Michelle

# Make fish_indiv called fish_id so can use with rest of code 
marked_fish <- marked_fish %>%
  dplyr::rename(fish_id = fish_indiv)

# Remove any observations where size is not recorded - 
marked_fish <- marked_fish %>%  # 3812 fish
  filter(size != "NA" & !is.na(size))

# Remove any observations where the date is not recorded (doesn't remove any)
marked_fish <- marked_fish %>% filter(!is.na(date))

##### Pull out recaptured fish, create recapture pairs
# Pull out fish captured more than once - 503 obs 
recap_fish <- marked_fish %>%
  group_by(fish_id) %>%
  summarize(ncaps = n(),
            year1 = min(year)) %>%
  filter(ncaps > 1)

# Find max number of recaptures for a fish
max_recaps <- max(recap_fish$ncaps)

# Pull out fish captured two through 8 (max_recaps) times
recaps_2X <- recap_fish %>% filter(ncaps == 2)
recaps_3X <- recap_fish %>% filter(ncaps == 3)
recaps_4X <- recap_fish %>% filter(ncaps == 4)
recaps_5X <- recap_fish %>% filter(ncaps == 5)
recaps_6X <- recap_fish %>% filter(ncaps == 6)
recaps_7X <- recap_fish %>% filter(ncaps == 7)
recaps_8X <- recap_fish %>% filter(ncaps == 8)

# Pull out sizes and time lapsed for the the various recapture pairs
recaps_2X_pair1 = findRecapPair(recaps_2X, marked_fish, 1, 2) #recap pair for fish caught 2X
recaps_3X_pair1 = findRecapPair(recaps_3X, marked_fish, 1, 2) #first recap pair for fish caught 3X (first and second encounters)
recaps_3X_pair2 = findRecapPair(recaps_3X, marked_fish, 2, 3) #second recap pair fish caught 3X (second and third encounters)
recaps_4X_pair1 = findRecapPair(recaps_4X, marked_fish, 1, 2) #first recap pair for fish caught 4X (first and second encounters)
recaps_4X_pair2 = findRecapPair(recaps_4X, marked_fish, 2, 3) #second recap pair for fish caught 4X (second and third encounters)
recaps_4X_pair3 = findRecapPair(recaps_4X, marked_fish, 3, 4) #third recap pair for fish caught 4X (third and fourth encounters)
recaps_5X_pair1 = findRecapPair(recaps_5X, marked_fish, 1, 2) #first and second encounters for fish caught 5X
recaps_5X_pair2 = findRecapPair(recaps_5X, marked_fish, 2, 3) #second and third encounters for fish caught 5X
recaps_5X_pair3 = findRecapPair(recaps_5X, marked_fish, 3, 4) #third and fourth encounters for fish caught 5X
recaps_5X_pair4 = findRecapPair(recaps_5X, marked_fish, 4, 5) #fourth and fifth encounters for fish caught 5X
recaps_6X_pair1 = findRecapPair(recaps_6X, marked_fish, 1, 2) #first and second encouters for fish caught 6X
recaps_6X_pair2 = findRecapPair(recaps_6X, marked_fish, 2, 3) #second and third encounters for fish caught 6X
recaps_6X_pair3 = findRecapPair(recaps_6X, marked_fish, 3, 4) #third and fourth encounters for fish caught 6X
recaps_6X_pair4 = findRecapPair(recaps_6X, marked_fish, 4, 5) #fourth and fifth encounters for fish caught 6X
recaps_6X_pair5 = findRecapPair(recaps_6X, marked_fish, 5, 6) #fifth and sixth encounters for fish caught 6X
recaps_7X_pair1 = findRecapPair(recaps_7X, marked_fish, 1, 2) #first and second encouters for fish caught 7X
recaps_7X_pair2 = findRecapPair(recaps_7X, marked_fish, 2, 3) #second and third encounters for fish caught 7X
recaps_7X_pair3 = findRecapPair(recaps_7X, marked_fish, 3, 4) #third and fourth encounters for fish caught 7X
recaps_7X_pair4 = findRecapPair(recaps_7X, marked_fish, 4, 5) #fourth and fifth encounters for fish caught 7X
recaps_7X_pair5 = findRecapPair(recaps_7X, marked_fish, 5, 6) #fifth and sixth encounters for fish caught 7X
recaps_7X_pair6 = findRecapPair(recaps_7X, marked_fish, 6, 7) #sixth and seventh encounters for fish caught 7X
recaps_8X_pair1 = findRecapPair(recaps_8X, marked_fish, 1, 2) #first and second encouters for fish caught 8X
recaps_8X_pair2 = findRecapPair(recaps_8X, marked_fish, 2, 3) #second and third encounters for fish caught 8X
recaps_8X_pair3 = findRecapPair(recaps_8X, marked_fish, 3, 4) #third and fourth encounters for fish caught 8X
recaps_8X_pair4 = findRecapPair(recaps_8X, marked_fish, 4, 5) #fourth and fifth encounters for fish caught 8X
recaps_8X_pair5 = findRecapPair(recaps_8X, marked_fish, 5, 6) #fifth and sixth encounters for fish caught 8X
recaps_8X_pair6 = findRecapPair(recaps_8X, marked_fish, 6, 7) #sixth and seventh encounters for fish caught 8X
recaps_8X_pair7 = findRecapPair(recaps_8X, marked_fish, 7, 8) #seventh and eighth encounters for fish caught 8X

# Join pairs together into one data frame - 763 pairs 
recap_pairs <- rbind(recaps_2X_pair1, recaps_3X_pair1, recaps_3X_pair2,
                     recaps_4X_pair1, recaps_4X_pair2, recaps_4X_pair3,
                     recaps_5X_pair1, recaps_5X_pair2, recaps_5X_pair3, recaps_5X_pair4,
                     recaps_6X_pair1, recaps_6X_pair2, recaps_6X_pair3, recaps_6X_pair4, recaps_6X_pair5,
                     recaps_7X_pair1, recaps_7X_pair2, recaps_7X_pair3, 
                     recaps_7X_pair4, recaps_7X_pair5, recaps_7X_pair6,
                     recaps_8X_pair1, recaps_8X_pair2, recaps_8X_pair3,
                     recaps_8X_pair4, recaps_8X_pair5, recaps_8X_pair6, recaps_8X_pair7)

# Filter out those captured on the same day - becomes 751 pairs
recap_pairs <- recap_pairs %>%
  filter(tal != 0)

# Add in percentage-of-year column for time 
recap_pairs <- recap_pairs %>%
  dplyr::rename(tal_days = tal) %>%
  mutate(tal = as.numeric(tal_days/365))

# Add in column for growth, growth per year, make size columns numeric, add in projected growth 1 year later
recap_pairs <- recap_pairs %>%
  mutate(L1 = as.numeric(L1),
         L2 = as.numeric(L2),
         growth = L2-L1,
         growth_per_year = growth/tal,
         L2_one_year_later = round(L1 + growth_per_year, digits = 1))  # projected growth one year later, based on growth-per-year

# Filter out just those recaptured about a year later - 265
recap_pairs_year <- recap_pairs %>%
  filter(tal_days > year_lower_limit & tal_days <= year_upper_limit) 

# Find those fish that have multiple recaptures that are about a year apart
multiple_year_recap_fish <- recap_pairs_year %>%
  group_by(fish_id) %>%
  summarize(n_year_caps = n())

########## Fitting growth models ##########

# Set a size range for making predictions from models (to plot)
size_range_sequence <- data.frame(L1 = seq(1, max_size, length = max_size*10))

##### Hart et al. 2009 method - just fit a basic linear regression (not enough multi-year fish with about a year in between to do a random mixed effects model)
# If just do a linear regression between Lt and Lt+1, can calculate K and Linf from y-intercept (b) and slope (m) - but doesn't take into account random effect or individual effects

### Regular linear model regression, no random effects or anything, using all fish recaptures within the time frame (including the 23 fish that have 2-3 recaptures that fit that)
model_1 <- lm(L2 ~ L1, data =  (recap_pairs_year))

model_1_k <- as.numeric(-log(model_1$coefficients[2]))  # 0.848 if use all fish captured about a year later (even multiple pairs per fish) 
model_1_Linf <- as.numeric(model_1$coefficients[1]/(1 - model_1$coefficients[2]))  # 10.763 if use all fish captured about a year later (even multiple pairs per fish) 

model_1_predictions <- predict.lm(model_1, newdata = size_range_sequence, se.fit = TRUE)

#### Run a bunch, choosing one pair for each multiple-times-recaptured scripts each time 
model_1_runs <- chooseRecapFitModel_TimeLimitPreFiltered(n_runs, recap_pairs_year, multiple_year_recap_fish)

model_1_runs <- model_1_runs %>%
  mutate(k_est = -log(slope_est),
         Linf_est = intercept_est/(1 - slope_est))

### Also tried a gam, with random effects by fish_id but really don't have that many fish with multiple long recaptures, didn't fit well

#################### Plots: ####################

# Plot histogram of Linf and k estimates for n_runs with choosing different recap pairs
Linf_plot <- ggplot(data = model_1_runs, aes(x = Linf_est)) +
  geom_histogram(bins = 40, color = "gray", fill = "gray") +
  geom_vline(xintercept = mean(model_1_runs$Linf_est), color = "black") +
  xlab("Linf (cm) estimate") + ggtitle("Linf: choosing pairs, 1 year") +
  theme_bw()

k_plot <- ggplot(data = model_1_runs, aes(x = k_est)) +
  geom_histogram(bins = 40, color = "gray", fill = "gray") +
  geom_vline(xintercept = mean(model_1_runs$k_est)) +
  xlab("k estimate") + ggtitle("k: choosing pairs, 1 year") +
  theme_bw()

pdf(file = here::here("Plots/Growth", "Linf_and_k_histogram_runs_choosing_pairs.pdf"), width=6, height=3)
plot_grid(Linf_plot, k_plot, nrow=1)
dev.off()

# Plot the data and linear model for fish caught about a year apart, models for only one recapture pair per fish, pairs selected randomly and models fit 1000x
pdf(file = here::here("Plots/Growth", "Data_L1_L2_with_fit_line_range_all_one_year_recap_fish.pdf"))
ggplot(data = recap_pairs_year, aes(x = L1, y = L2)) +
  geom_point(shape = 1) +
  geom_abline(aes(intercept = mean(model_1_runs$intercept_est), slope = mean(model_1_runs$slope_est)), color = "black") +
  geom_ribbon(aes(x=seq(from=2.5, to=12.5,length.out = length(recap_pairs_year$L1)),
                  ymin = (min(model_1_runs$intercept_est) + min(model_1_runs$slope_est)*seq(from=2.5, to=12.5,length.out = length(recap_pairs_year$L1))),
                  ymax = (max(model_1_runs$intercept_est) + max(model_1_runs$slope_est)*seq(from=2.5, to=12.5,length.out = length(recap_pairs_year$L1)))), fill = "light gray", alpha = 0.5) +
  xlab("Length (cm) at year t") + ylab("Length (cm) at year t+1") +
  ggtitle("Model fits across runs with data") +
  theme_bw()
dev.off()

#################### Saving output: ####################
growth_info_estimate = model_1_runs  # saving it with different name in case change input later...
save(recap_pairs_year, file = here::here("Data/Script_outputs", "recap_pairs_year.RData"))  # saving all recapture pairs caught about a year apart, for plotting purposes
save(growth_info_estimate, file = here::here("Data/Script_outputs", "growth_info_estimate.RData"))

